import { Router } from "express";
import courseRoutes from "./course.routes";
import enrollmentRoutes from "./enrollment.routes";
import blogRoutes from "./blog.routes";
import blogCategoryRoutes from "./blogCategory.routes";
import studentRoutes from "./student.routes";
import certificateRoutes from "./certificate.routes";
import trainerRoutes from "./trainer.routes";
import adminRoutes from "./admin.routes";
import reviewRoutes from "./review.routes";
import galleryRoutes from "./gallery.routes";
import referralRoutes from "./referral.routes";
import categoryRoutes from "./category.routes";
import uploadRoutes from "./upload.routes";
import couponRoutes from "./coupon.routes";
import trainerRequestRoutes from "./trainerRequest.routes";
const router = Router();

router.use("/courses", courseRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/blogs", blogRoutes);
router.use("/blog-categories", blogCategoryRoutes);
router.use("/students", studentRoutes);
router.use("/certificates", certificateRoutes);
router.use("/trainers", trainerRoutes);
router.use("/admin", adminRoutes);
router.use("/reviews", reviewRoutes);
router.use("/gallery", galleryRoutes);
router.use("/categories", categoryRoutes);
router.use("/referrals", referralRoutes);
router.use("/upload", uploadRoutes);
router.use("/coupons", couponRoutes);
router.use("/trainer-requests", trainerRequestRoutes);
export default router;